### ISSUE TITLE
Paste bug with path contains space character

### ISSUE THREAD

**Issue by zooeywm** [TD-Sky/sudo.yazi#1]
In yazi, When I use sudo.yazi paste with `/home/xxx/Downloads/Telegram\ Desktop/somfile`
It returns with error:
```
cp: cannot stat '/home/xxx/Downloads/Telegram': No such file or directory
cp: cannot stat 'Desktop/somfile': No such file or directory
```
Seems the plugin should recognize `Telegram Desktop` and replace with `Telegram\ Desktop` with regex.

**Comment by TD-Sky** [comment]
Fix in https://github.com/TD-Sky/sudo.yazi/commit/198d471f4d0ad609a4d87c5931e802d4c4a5dd8f
